config/routes.rb
Rails.application.routes.draw do
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  resources :projects, only: [ :show, :update ] do
    resources :comments, only: [ :create ], controller: "comments"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :project
  validates :comment, :commentor, :project, presence: true
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :comments
  has_many :project_histories

  validates :status, :name, presence: true
  validates :status, inclusion: { in: %w[ready in_progress complete] }
end

app/models/project_history.rb
class ProjectHistory < ApplicationRecord
  belongs_to :project

  validates :change, :project, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  rescue_from ActiveRecord::RecordNotFound do
    render file: "#{Rails.root}/public/404.html",  layout: false, status: :not_found
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(comment_params.merge!(project_id: project_id))
    if @comment.persisted?
      flash[:notice] = "Comment saved"

      ProjectHistoryCreator.new(
        project_id,
        "New Comment: comment: #{comment_params[:comment]} commentor: #{comment_params[:commentor]}"
      ).call

      redirect_to project_path(project_id)
    else
      flash[:error] = @comment.errors.full_messages
      render status: :unprocessable_content, layout: false
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:comment, :commentor)
  end

  def project_id
    params.require(:project_id)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def show
    @project = Project.find(params[:id])
    @comments = @project.comments.order(created_at: :desc)
    @histories = @project.project_histories.order(created_at: :desc)
  end

  def update
    @project = Project.find(params[:id])

    if @project.update(project_params)
      ProjectHistoryCreator.new(
        params[:id],
        "Project status change to: #{project_params[:status]}"
      ).call

      flash[:notice] = "Project has been updated"
      redirect_to @project
    else
      flash[:error] = @project.errors.full_messages
      render :show
    end
  end

  private

  def project_params
    params.require(:project).permit(:status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Project Comments" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/show.html.erb
<% if flash[:error] %>
  <h3>Please fix the following errors: </h3>
  <% flash[:error].each do |error| %>
    <div>
      <p>* <%= error %></p>
    </div>
  <% end %>
<% end %>

<% if flash[:notice]%>
  <div>
    <p><%= flash[:notice] %></p>
  </div>
<% end %>

<h1><%= @project.name %></h1>

<p>Status: <%= @project.status.humanize %></p>

<%= form_with model: @project do |form| %>
  <%= form.label :status, "Change project status" %>
  <%= form.select :status, [
    ["Ready", "ready"],
    ["In Progress", "in_progress"],
    ["Complete", "complete"]
  ] %>

  <%= form.submit "Update status" %>
<% end %>

<h2> Comments </h2>
<h3> New comment</h3>
  <%= form_for :comment, url: project_comments_path(@project) do |form| %>
    <%= form.label :comment, "Comment" %>
    <%= form.text_area :comment %>

    <%= form.label :commentor, "Name of commentor" %>
    <%= form.text_field :commentor %>

    <%= form.submit "Add comment" %>
  <% end %>
<% if !@comments.empty? %>
  <ul>
    <% @comments.each do |comment| %>
      <li>
        <p>Comment: <%= comment.comment %></p>
        <p>Name: <%= comment.commentor %></p>
      </li>
    <% end %>
  </ul>
<% else %>
  <p> No comments yet!</p>
<% end %>

<h2> Project History </h2>
<% if !@histories.empty? %>
  <ul>
    <% @histories.each do |history| %>
      <li><p>Change: <%= history.change %> Time: <%= history.created_at %></p></li>
    <% end %>
  </ul>
<% else %>
  <p>No history yet</p>
<% end %>